import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AppProviders } from "@/providers";
import { FloatingDock } from "@/components/floating-dock";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProviders>
          <main className="flex-1 overflow-x-hidden bg-background text-foreground flex flex-col min-h-screen">
            <div className="flex-1 p-6 pb-32">
              {children}
            </div>
          </main>
          <FloatingDock />
        </AppProviders>
      </body>
    </html>
  );
}
