import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppProviders } from "@/providers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProviders>
          <SidebarProvider>
            <AppSidebar />
            <main className="flex-1 overflow-x-hidden bg-background text-foreground flex flex-col min-h-screen">
              <header className="flex h-14 shrink-0 items-center justify-between border-b border-border bg-card px-4 sm:px-6">
                <div className="flex items-center gap-4">
                  <SidebarTrigger className="-ml-2" />
                </div>
              </header>
              <div className="flex-1 p-6">
                {children}
              </div>
            </main>
          </SidebarProvider>
        </AppProviders>
      </body>
    </html>
  );
}
